url: https://edu.legaltech.center/summer-school
baseurl: /summer-school
destination: _site/summer-school

# Site settings
title: Legal Tech Center
email: edu@legaltech.center?subject='Summer School Legal Tech in Berlin'
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Florian Glatz
  pic: florian
  position: Mitveranstalter und Dozent
  social:
    - title: twitter
      url: https://twitter.com/heckerhut
    - title: linkedin
      url: https://www.linkedin.com/in/florianglatz/
- name: Stephan Breidenbach
  pic: stephan
  position: Mitveranstalter und Dozent
  social:
    - title: twitter
      url: https://twitter.com/stebreidenbach/
    - title: linkedin
      url: https://www.linkedin.com/in/stephan-breidenbach-04b678111/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/legaltechcenter/
  - title: facebook
    url: https://www.facebook.com/legaltechcenter.berlin/
  - title: github
    url: http://github.com/hacking-law/

# Postal address (add as many lines as necessary)
address:
  - line: Alt-Moabit 2
  - line: 10557 Berlin

# Build settings
markdown: kramdown
permalink: pretty